title: cc7623's guide
description: appleinternal / jailbreak (hacker theme go brrr)
google_analytics: 
show_downloads: false
theme: pages-themes/hacker@v0.2.0
Retry-After: 1

plugins:
  - jekyll-include-cache
  - gemfile
