title: cc7623's guide
description: appleinternal / jailbreak (hacker theme go brrr)
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker
Retry-After: 1

plugins:
  - jekyll-include-cache
  - gemfile
